site:
  title: KakeiBro
  # the 404 page and sitemap files only get generated when the url property is set
  #url: https://antora.gitlab.io/demo/docs-site
  start_page: kakeibro-docs::index.adoc
content:
  sources:
  - url: ../docs
    branches: main
    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
    edit_url: false
    start_path: content
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    plantuml-server-url: http://www.plantuml.com/plantuml
    plantuml-fetch-diagram: true
  extensions:
  - asciidoctor-plantuml
ui:
  bundle:
    url: ./ui.zip
    snapshot: true
