site:
  title: KakeiBro
  # the 404 page and sitemap files only get generated when the url property is set
  #url: https://antora.gitlab.io/demo/docs-site
  start_page: kakeibro-docs::index.adoc
content:
  sources:
  - url: ../docs
    branches: main
    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
    edit_url: false
    start_path: content
antora:
  extensions:
    - require: 'antora-shiki-extension'
      theme: 'rose-pine'
      languages:
        - js
        - asciidoc
        - yaml
      register_languages:
        - id: 'typescript'
          scope_name: 'source.ts'
          grammar_path: ./shiki_syntaxes/typescript.json
          alias: ['ts']
        - id: 'tsx'
          scope_name: 'source.tsx'
          grammar_path: ./shiki_syntaxes/tsx.json
          alias: ['tsx']
        - id: 'csharp'
          scope_name: 'source.cs'
          grammar_path: ./shiki_syntaxes/csharp.json
          alias: ['cs']
      use_line_numbers: true
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    plantuml-server-url: http://www.plantuml.com/plantuml
    plantuml-fetch-diagram: true
    source-highlighter: shiki
    page-toclevels: 4@
  extensions:
  - asciidoctor-plantuml
ui:
  bundle:
    url: ./ui.zip
    snapshot: true
